In [1]:
import sys
import pandas as pd
import os
import numpy as np
from scipy import stats
import re
import csv
import tabulate
import math as m
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')
import scipy.io

path_data = '/media/cbclab/MARIADAFON1T/Analysis_2020/fixs/'

In [18]:
for x in os.listdir(path_data):
    if x.startswith("16"):
        print(x)
        print('# fixs: ',len(pd.read_csv(path_data+x)))
        print('\n')

16subj_hard&easy_for_unfold.csv
# fixs 735


16subj_hardVSeasy_for_unfold.csv
# fixs 527


16subj_NTFvsNTO_for_unfold.csv
# fixs 8654


16subj_NTFvsNTO_postarget_for_unfold.csv
# fixs 893


16subj_NTFvsNTO_pretarget_for_unfold.csv
# fixs 2017


16subj_NTOvsNTF_for_unfold.csv
# fixs 15356


16subj_targetAS_for_unfold.csv
# fixs 2773


16subj_VSeasy_vs_EXobj_correct_for_unfold.csv
# fixs 1818


16subj_VShard_vs_EXobj_correct_for_unfold.csv
# fixs 1812


16subj_VSNTpostvsEX_for_unfold.csv
# fixs 9928


16subj_VSNTpostvsEX_for_unfold_GlobalStandarisedCenteredRank.csv
# fixs 5127


16subj_VSNTpostvsEX_for_unfold_GlobalStandarisedRank_.csv
# fixs 5127


16subj_VSNTpostvsEX_for_unfold_withoutNanStandarisedRank.csv
# fixs 5127


16subj_VSNTpre_VSNTpost_for_unfold.csv
# fixs 8653


16subj_VSNTvsEX_correct_for_unfold.csv
# fixs 7234


16subj_VSNTvsEX_correct_withoutFix1_for_unfold.csv
# fixs 5859


16subj_VSNTvsEX_for_unfold.csv
# fixs 5309


16subj_VSNTvsEX_for_unfold_testNANs.csv
# fixs 11945


In [4]:
f1 = '16subj_VSNTpostvsEX_for_unfold_GlobalStandarisedCenteredRank.csv'
f2 = '16subj_NTFvsNTO_for_unfold.csv'

In [6]:
df1 = pd.read_csv(path_data+f1)

In [7]:
df2 = pd.read_csv(path_data+f2)

In [8]:
df1.columns

Index(['refix', 'pretarget', 'multifix', 'urevent', 'tonset', 'dur_added',
       'rank', 'first_rank', 'stposrel', 'stposabs', 'n', 'x', 'y', 'istarget',
       'isdistractor', 'distractor_cat', 'ditractor_atr', 'trial_targetseen',
       'trial_correct', 'trial_cat', 'trial_resp', 'trial_atr', 'trial_type',
       'trial_cattype', 'trial_number', 'trial_subject', 'trial_bgn_latency',
       'VSNT_EX', 'isEX', 'Nrank', 'N_subj_rank', 'NC_subj_rank', 'NC_rank'],
      dtype='object')

In [9]:
df1['trial_resp'].unique()

array(['P', 'A'], dtype=object)

In [10]:
df1[df1['VSNT_EX']==1]['trial_resp'].unique()

array(['P'], dtype=object)

In [11]:
df1[df1['VSNT_EX']==0]['trial_resp'].unique()

array(['A'], dtype=object)

In [12]:
len(df1)

5127

In [13]:
len(df2)

8654

In [14]:
df2.columns

Index(['refix', 'pretarget', 'multifix', 'urevent', 'tonset', 'dur_added',
       'rank', 'first_rank', 'stposrel', 'stposabs', 'n', 'x', 'y', 'istarget',
       'isdistractor', 'distractor_cat', 'ditractor_atr', 'trial_targetseen',
       'trial_correct', 'trial_cat', 'trial_resp', 'trial_atr', 'trial_type',
       'trial_cattype', 'trial_number', 'trial_subject', 'trial_bgn_latency',
       'NTF_NTO'],
      dtype='object')

In [17]:
df2['trial_type'].unique()

array(['VS'], dtype=object)

In [15]:
set(list(df2.columns))-set(list(df1.columns))

{'NTF_NTO'}

In [16]:
set(list(df1.columns))-set(list(df2.columns))

{'NC_rank', 'NC_subj_rank', 'N_subj_rank', 'Nrank', 'VSNT_EX', 'isEX'}

In [19]:
df1['Nrank'].unique()

array([0.        , 0.33333333, 1.        , 0.11111111, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 0.5       ,
       0.22222222, 0.1       , 0.3       , 0.4       , 0.6       ,
       0.7       , 0.8       , 0.9       , 0.2       , 0.14285714,
       0.28571429, 0.42857143, 0.57142857, 0.71428571, 0.85714286,
       0.125     , 0.375     , 0.625     , 0.75      , 0.875     ,
       0.25      , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 0.16666667, 0.83333333, 0.08333333, 0.41666667,
       0.91666667])

In [20]:
df1['rank'].unique()

array([ 2.,  3.,  5.,  6.,  7.,  8.,  9., 10., 11.,  4., 12., 13., 14.])

In [21]:
df1[(df1['trial_subject']=='E01')]

refix  pretarget  multifix  urevent    tonset  dur_added  rank  \
0        0        1.0         0    23231  1.039062   0.138672   2.0   
1        0        1.0         1    23232  1.240234   0.119141   3.0   
2        0        1.0         0    23236  1.978516   0.126953   5.0   
3        0        0.0         0    23249  0.808594   0.271484   2.0   
4        0        0.0         0    23250  1.142578   0.220703   3.0   
..     ...        ...       ...      ...       ...        ...   ...   
476      0        0.0         0    29116  1.298828   0.140625   3.0   
477      0        0.0         0    29117  1.494141   0.238281   4.0   
478      0        0.0         0    29118  1.763672   0.199219   5.0   
479      0        0.0         0    29119  2.058594   0.308594   6.0   
480      0        0.0         1    29121  2.763672   0.232422   7.0   

     first_rank  stposrel  stposabs  ...  trial_cattype  trial_number  \
0           1.0         8        47  ...              O             2   
1           1.0        13        66  ...              O             2   
2           0.0         6        42  ...              O             2   
3           1.0         3        10  ...              F             3   
4           1.0         7        28  ...              F             3   
..          ...       ...       ...  ...            ...           ...   
476         1.0        12        65  ...              O           213   
477         1.0         8        39  ...              O           213   
478         0.0        10        48  ...              O           213   
479         0.0        13        69  ...              O           213   
480         0.0         5        27  ...              O           213   

     trial_subject  trial_bgn_latency  VSNT_EX isEX     Nrank  N_subj_rank  \
0              E01           4.400391      1.0  0.0  0.000000     0.000000   
1              E01           4.400391      1.0  0.0  0.333333     0.090909   
2              E01           4.400391      1.0  0.0  1.000000     0.272727   
3              E01           8.599609      0.0  1.0  0.000000     0.000000   
4              E01           8.599609      0.0  1.0  0.111111     0.090909   
..             ...                ...      ...  ...       ...          ...   
476            E01         890.435547      0.0  1.0  0.200000     0.090909   
477            E01         890.435547      0.0  1.0  0.400000     0.181818   
478            E01         890.435547      0.0  1.0  0.600000     0.272727   
479            E01         890.435547      0.0  1.0  0.800000     0.363636   
480            E01         890.435547      0.0  1.0  1.000000     0.454545   

     NC_subj_rank   NC_rank  
0       -0.500000 -0.500000  
1       -0.409091 -0.166667  
2       -0.227273  0.500000  
3       -0.500000 -0.500000  
4       -0.409091 -0.388889  
..            ...       ...  
476     -0.409091 -0.300000  
477     -0.318182 -0.100000  
478     -0.227273  0.100000  
479     -0.136364  0.300000  
480     -0.045455  0.500000  

[481 rows x 33 columns]

In [22]:
df1[(df1['trial_subject']=='E01')]['trial_number'].unique()

array([  2,   3,   4,   5,   9,  11,  13,  15,  16,  18,  21,  22,  25,
        28,  29,  37,  38,  40,  44,  45,  47,  49,  51,  56,  63,  64,
        66,  67,  71,  76,  78,  79,  81,  84,  85,  87,  88,  94,  96,
        98,  99, 101, 102, 103, 104, 112, 116, 118, 119, 120, 121, 122,
       127, 128, 133, 136, 139, 141, 147, 148, 149, 151, 152, 153, 154,
       155, 156, 161, 162, 163, 168, 169, 170, 171, 173, 178, 180, 181,
       184, 186, 187, 188, 189, 191, 192, 193, 197, 199, 200, 201, 203,
       209, 213])

In [23]:
len(df1[(df1['trial_subject']=='E01')]['trial_number'].unique())

93

In [24]:
df1.columns

Index(['refix', 'pretarget', 'multifix', 'urevent', 'tonset', 'dur_added',
       'rank', 'first_rank', 'stposrel', 'stposabs', 'n', 'x', 'y', 'istarget',
       'isdistractor', 'distractor_cat', 'ditractor_atr', 'trial_targetseen',
       'trial_correct', 'trial_cat', 'trial_resp', 'trial_atr', 'trial_type',
       'trial_cattype', 'trial_number', 'trial_subject', 'trial_bgn_latency',
       'VSNT_EX', 'isEX', 'Nrank', 'N_subj_rank', 'NC_subj_rank', 'NC_rank'],
      dtype='object')

In [25]:
subj1 = df1[(df1['trial_subject']=='E01')]

In [26]:
subj1['refix'].unique()

array([0, 1])

In [27]:
subj1['pretarget'].unique()

array([1., 0.])

In [28]:
subj1[subj1['pretarget']==0]['isEX'].unique()

array([1.])

In [29]:
subj1[subj1['isEX']==1]['pretarget'].unique()

array([0.])

In [30]:
df1[df1['trial_type']=='EX']['pretarget'].unique()

array([0.])

In [31]:
subj1['multifix'].unique()

array([0, 1])

In [32]:
subj1['dur_added'].min()

0.1015625

In [33]:
subj1['dur_added'].max()

0.56640625

In [34]:
len(subj1['rank'].unique())

12

In [35]:
len(subj1)

481

In [36]:
subj1['first_rank'].unique()

array([1., 0.])

In [37]:
subj1['istarget'].unique()

array([0])

In [38]:
subj1['isdistractor'].unique()

array([1])

In [39]:
subj1['distractor_cat'].unique()

array(['faces', 'objects'], dtype=object)

In [40]:
subj1['ditractor_atr'].unique()

array(['male', 'small', 'female', 'big'], dtype=object)

In [41]:
subj1['trial_targetseen'].unique()

array([1, 0])

In [42]:
subj1[subj1['VSNT_EX']==1]['trial_targetseen'].unique()

array([1])

In [43]:
subj1['trial_correct'].unique()

array([1])

In [44]:
subj1['trial_cat'].unique()

array(['objects', 'faces'], dtype=object)

In [45]:
subj1[subj1['VSNT_EX']==1]['trial_resp'].unique()

array(['P'], dtype=object)

In [46]:
subj1['trial_atr'].unique()

array(['big', 'female', 'small', 'male'], dtype=object)

In [47]:
subj1[subj1['VSNT_EX']==1]['trial_type'].unique()

array(['VS'], dtype=object)

In [48]:
subj1['trial_cattype'].unique()

array(['O', 'F', 'I'], dtype=object)

In [49]:
len(subj1['trial_number'].unique())

93

In [50]:
subj1['trial_number'].unique()

array([  2,   3,   4,   5,   9,  11,  13,  15,  16,  18,  21,  22,  25,
        28,  29,  37,  38,  40,  44,  45,  47,  49,  51,  56,  63,  64,
        66,  67,  71,  76,  78,  79,  81,  84,  85,  87,  88,  94,  96,
        98,  99, 101, 102, 103, 104, 112, 116, 118, 119, 120, 121, 122,
       127, 128, 133, 136, 139, 141, 147, 148, 149, 151, 152, 153, 154,
       155, 156, 161, 162, 163, 168, 169, 170, 171, 173, 178, 180, 181,
       184, 186, 187, 188, 189, 191, 192, 193, 197, 199, 200, 201, 203,
       209, 213])

In [51]:
set([  2,   3,   4,   5,   9,  11,  13,  15,  16,  18,  21,  22,  23,
        25,  28,  29,  37,  38,  40,  44,  45,  47,  49,  51,  52,  54,
        55,  56,  63,  64,  66,  67,  71,  76,  78,  79,  80,  81,  84,
        85,  86,  87,  88,  94,  96,  98,  99, 101, 102, 103, 104, 112,
       116, 118, 119, 120, 121, 122, 127, 128, 133, 136, 139, 141, 147,
       148, 149, 151, 152, 153, 154, 155, 156, 161, 162, 163, 168, 169,
       170, 171, 173, 178, 180, 181, 184, 186, 187, 188, 189, 190, 191,
       192, 193, 197, 199, 200, 201, 202, 203, 207, 209, 213])-set(list(subj1['trial_number'].unique()))

{23, 52, 54, 55, 80, 86, 190, 202, 207}

In [52]:
subj1['Nrank'].unique()

array([0.        , 0.33333333, 1.        , 0.11111111, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 0.5       ,
       0.22222222, 0.1       , 0.3       , 0.4       , 0.6       ,
       0.7       , 0.8       , 0.9       , 0.2       , 0.14285714,
       0.28571429, 0.42857143, 0.57142857, 0.71428571, 0.85714286,
       0.125     , 0.375     , 0.625     , 0.75      , 0.875     ,
       0.25      , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 0.16666667, 0.83333333])

In [53]:
df1.groupby(['trial_subject', 'trial_number']).size()

trial_subject  trial_number
E01            2                3
               3                9
               4                3
               5               10
               9               10
                               ..
J12            193             10
               194              4
               202              3
               208              4
               213              7
Length: 1049, dtype: int64